name: Docker Image CI

on:
  push:
  schedule:
    - cron: '25 18 * * WED'
  workflow_dispatch: {}

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: |
            jzylks/centos-django-rpm/centos-django-rpm:latest
            jzylks/centos-django-rpm/centos-django-rpm:${{ github.sha }}-${{ github.run_number }}
