name: Docker Image CI

on:
  - push
  - 
    schedule:
      - cron: '13 13 * * WED'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag centos-django-rpm:$(date +%s)
