name: Docker Image CI

on:
  push:
  schedule:
    - cron: '25 18 * * WED'
  workflow_dispatch: {}

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            jzylks/centos-django-rpm
          tags: |
            type=ref,event=branch
            type=ref,event=pr
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=registry,ref=jzylks/centos-django-rpm:latest
          cache-to: type=inline
          tags: ghcr.io/jzylks/centos-django-rpm:latest
